# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

community_category = Category.where(name: 'community').first_or_create(name: 'community')
housing_category = Category.where(name: 'housing').first_or_create(name: 'housing')
personals_category = Category.where(name: 'personals').first_or_create(name: 'personals')
forsale_category = Category.where(name: 'for sale').first_or_create(name: 'for sale')
jobs_category = Category.where(name: 'jobs').first_or_create(name: 'jobs')
services_category = Category.where(name: 'services').first_or_create(name: 'services')
discussionforums_category = Category.where(name: 'discussion forum').first_or_create(name: 'discussion forum')
gigs_category = Category.where(name: 'gigs').first_or_create(name: 'gigs')

Subcategory.where(name: 'activities', category_id: community_category.id).first_or_create(name: 'activities', category_id: community_category.id)
Subcategory.where(name: 'classes', category_id: community_category.id).first_or_create(name: 'classes', category_id: community_category.id)
Subcategory.where(name: 'events', category_id: community_category.id).first_or_create(name: 'events', category_id: community_category.id)
Subcategory.where(name: 'musicians', category_id: community_category.id).first_or_create(name: 'musicians', category_id: community_category.id)
Subcategory.where(name: 'news', category_id: community_category.id).first_or_create(name: 'news', category_id: community_category.id)
Subcategory.where(name: 'general', category_id: community_category.id).first_or_create(name: 'general', category_id: community_category.id)
Subcategory.where(name: 'pets', category_id: community_category.id).first_or_create(name: 'pets', category_id: community_category.id)

Subcategory.where(name: 'apts/housing for rent', category_id: housing_category.id).first_or_create(name: 'apts/housing for rent', category_id: housing_category.id)
Subcategory.where(name: 'apts wanted', category_id: housing_category.id).first_or_create(name: 'apts wanted', category_id: housing_category.id)
Subcategory.where(name: 'housing swap', category_id: housing_category.id).first_or_create(name: 'housing swap', category_id: housing_category.id)
Subcategory.where(name: 'office & command', category_id: housing_category.id).first_or_create(name: 'office & command', category_id: housing_category.id)
Subcategory.where(name: 'parking & storage', category_id: housing_category.id).first_or_create(name: 'parking & storage', category_id: housing_category.id)
Subcategory.where(name: 'real estate -by broker', category_id: housing_category.id).first_or_create(name: 'real estate -by broker', category_id: housing_category.id)
Subcategory.where(name: 'real estate -by owner', category_id: housing_category.id).first_or_create(name: 'real estate -by owner', category_id: housing_category.id)
Subcategory.where(name: 'room & shares', category_id: housing_category.id).first_or_create(name: 'room & shares', category_id: housing_category.id)
Subcategory.where(name: 'rooms wanted', category_id: housing_category.id).first_or_create(name: 'rooms wanted', category_id: housing_category.id)
Subcategory.where(name: 'sublets & temporary', category_id: housing_category.id).first_or_create(name: 'sublets & temporary', category_id: housing_category.id)
Subcategory.where(name: 'sublet/temporary wanted', category_id: housing_category.id).first_or_create(name: 'sublet/temporary wanted', category_id: housing_category.id)
Subcategory.where(name: 'vacation renters', category_id: housing_category.id).first_or_create(name: 'vacation renters', category_id: housing_category.id)

Subcategory.where(name: 'antiques', category_id: forsale_category.id).first_or_create(name: 'antiques', category_id: forsale_category.id)
Subcategory.where(name: 'appliances', category_id: forsale_category.id).first_or_create(name: 'appliances', category_id: forsale_category.id)
Subcategory.where(name: 'arts+crafts', category_id: forsale_category.id).first_or_create(name: 'arts+crafts', category_id: forsale_category.id)
Subcategory.where(name: 'atv/utv/sno', category_id: forsale_category.id).first_or_create(name: 'atv/utv/sno', category_id: forsale_category.id)
Subcategory.where(name: 'auto parts', category_id: forsale_category.id).first_or_create(name: 'auto parts', category_id: forsale_category.id)
Subcategory.where(name: 'baby+kid', category_id: forsale_category.id).first_or_create(name: 'baby+kid', category_id: forsale_category.id)
Subcategory.where(name: 'barter', category_id: forsale_category.id).first_or_create(name: 'barter', category_id: forsale_category.id)
Subcategory.where(name: 'beauty+hlth', category_id: forsale_category.id).first_or_create(name: 'beauty+hlth', category_id: forsale_category.id)
Subcategory.where(name: 'bikes', category_id: forsale_category.id).first_or_create(name: 'bikes', category_id: forsale_category.id)
Subcategory.where(name: 'books', category_id: forsale_category.id).first_or_create(name: 'books', category_id: forsale_category.id)
Subcategory.where(name: 'business', category_id: forsale_category.id).first_or_create(name: 'business', category_id: forsale_category.id)
Subcategory.where(name: 'boats', category_id: forsale_category.id).first_or_create(name: 'boats', category_id: forsale_category.id)
Subcategory.where(name: 'business', category_id: forsale_category.id).first_or_create(name: 'business', category_id: forsale_category.id)
Subcategory.where(name: 'cars+trucks', category_id: forsale_category.id).first_or_create(name: 'cars+trucks', category_id: forsale_category.id)
Subcategory.where(name: 'cds/dvd/vhs', category_id: forsale_category.id).first_or_create(name: 'cds/dvd/vhs', category_id: forsale_category.id)
Subcategory.where(name: 'cell phones', category_id: forsale_category.id).first_or_create(name: 'cell phones', category_id: forsale_category.id)
Subcategory.where(name: 'collectibles', category_id: forsale_category.id).first_or_create(name: 'collectibles', category_id: forsale_category.id)
Subcategory.where(name: 'computers', category_id: forsale_category.id).first_or_create(name: 'computers', category_id: forsale_category.id)
Subcategory.where(name: 'electronices', category_id: forsale_category.id).first_or_create(name: 'electronices', category_id: forsale_category.id)
Subcategory.where(name: 'farm+garden', category_id: forsale_category.id).first_or_create(name: 'farm+garden', category_id: forsale_category.id)
Subcategory.where(name: 'free', category_id: forsale_category.id).first_or_create(name: 'free', category_id: forsale_category.id)
Subcategory.where(name: 'furniture', category_id: forsale_category.id).first_or_create(name: 'furniture', category_id: forsale_category.id)
Subcategory.where(name: 'garage sale', category_id: forsale_category.id).first_or_create(name: 'garage sale', category_id: forsale_category.id)
Subcategory.where(name: 'general', category_id: forsale_category.id).first_or_create(name: 'general', category_id: forsale_category.id)
Subcategory.where(name: 'heavy equip', category_id: forsale_category.id).first_or_create(name: 'heavy equip', category_id: forsale_category.id)
Subcategory.where(name: 'household', category_id: forsale_category.id).first_or_create(name: 'household', category_id: forsale_category.id)
Subcategory.where(name: 'jewelry', category_id: forsale_category.id).first_or_create(name: 'jewelry', category_id: forsale_category.id)
Subcategory.where(name: 'materials', category_id: forsale_category.id).first_or_create(name: 'materials', category_id: forsale_category.id)
Subcategory.where(name: 'motorcycles', category_id: forsale_category.id).first_or_create(name: 'motorcycles', category_id: forsale_category.id)
Subcategory.where(name: 'music instr', category_id: forsale_category.id).first_or_create(name: 'music instr', category_id: forsale_category.id)
Subcategory.where(name: 'photo+video', category_id: forsale_category.id).first_or_create(name: 'photo+video', category_id: forsale_category.id)
Subcategory.where(name: 'rvs+camp', category_id: forsale_category.id).first_or_create(name: 'rvs+camp', category_id: forsale_category.id)
Subcategory.where(name: 'sporting', category_id: forsale_category.id).first_or_create(name: 'sporting', category_id: forsale_category.id)
Subcategory.where(name: 'tickets', category_id: forsale_category.id).first_or_create(name: 'tickets', category_id: forsale_category.id)
Subcategory.where(name: 'tools', category_id: forsale_category.id).first_or_create(name: 'tools', category_id: forsale_category.id)
Subcategory.where(name: 'toys+games', category_id: forsale_category.id).first_or_create(name: 'toys+games', category_id: forsale_category.id)
Subcategory.where(name: 'video gaming', category_id: forsale_category.id).first_or_create(name: 'video gaming', category_id: forsale_category.id)
Subcategory.where(name: 'wanted', category_id: forsale_category.id).first_or_create(name: 'wanted', category_id: forsale_category.id)

Subcategory.where(name: 'computer', category_id: gigs_category.id).first_or_create(name: 'computer', category_id: gigs_category.id)
Subcategory.where(name: 'creative', category_id: gigs_category.id).first_or_create(name: 'creative', category_id: gigs_category.id)
Subcategory.where(name: 'crew', category_id: gigs_category.id).first_or_create(name: 'crew', category_id: gigs_category.id)
Subcategory.where(name: 'domestic', category_id: gigs_category.id).first_or_create(name: 'domestic', category_id: gigs_category.id)
Subcategory.where(name: 'event', category_id: gigs_category.id).first_or_create(name: 'event', category_id: gigs_category.id)
Subcategory.where(name: 'labor', category_id: gigs_category.id).first_or_create(name: 'labor', category_id: gigs_category.id)
Subcategory.where(name: 'talent', category_id: gigs_category.id).first_or_create(name: 'talent', category_id: gigs_category.id)
Subcategory.where(name: 'writing', category_id: gigs_category.id).first_or_create(name: 'writing', category_id: gigs_category.id)

Subcategory.where(name: 'strictly platonic', category_id: personals_category.id).first_or_create(name: 'strictly platonic', category_id: personals_category.id)
Subcategory.where(name: 'women seeking women', category_id: personals_category.id).first_or_create(name: 'women seeking women', category_id: personals_category.id)
Subcategory.where(name: 'women seeking men', category_id: personals_category.id).first_or_create(name: 'women seeking men', category_id: personals_category.id)
Subcategory.where(name: 'men seeking women', category_id: personals_category.id).first_or_create(name: 'men seeking women', category_id: personals_category.id)
Subcategory.where(name: 'men seeking men', category_id: personals_category.id).first_or_create(name: 'men seeking men', category_id: personals_category.id)
Subcategory.where(name: 'misc romance', category_id: personals_category.id).first_or_create(name: 'misc romance', category_id: personals_category.id)
Subcategory.where(name: 'casual encounters', category_id: personals_category.id).first_or_create(name: 'casual encounters', category_id: personals_category.id)
Subcategory.where(name: 'missed connections', category_id: personals_category.id).first_or_create(name: 'missed connections', category_id: personals_category.id)
Subcategory.where(name: 'rants and raves', category_id: personals_category.id).first_or_create(name: 'rants and raves', category_id: personals_category.id)

Subcategory.where(name: 'automative', category_id: services_category.id).first_or_create(name: 'automative', category_id: services_category.id)
Subcategory.where(name: 'beauty', category_id: services_category.id).first_or_create(name: 'beauty', category_id: services_category.id)
Subcategory.where(name: 'computer', category_id: services_category.id).first_or_create(name: 'computer', category_id: services_category.id)
Subcategory.where(name: 'creative', category_id: services_category.id).first_or_create(name: 'creative', category_id: services_category.id)
Subcategory.where(name: 'cycle', category_id: services_category.id).first_or_create(name: 'cycle', category_id: services_category.id)
Subcategory.where(name: 'event', category_id: services_category.id).first_or_create(name: 'event', category_id: services_category.id)
Subcategory.where(name: 'farm+garden', category_id: services_category.id).first_or_create(name: 'farm+garden', category_id: services_category.id)
Subcategory.where(name: 'financial', category_id: services_category.id).first_or_create(name: 'financial', category_id: services_category.id)
Subcategory.where(name: 'household', category_id: services_category.id).first_or_create(name: 'household', category_id: services_category.id)
Subcategory.where(name: 'labor/move', category_id: services_category.id).first_or_create(name: 'labor/move', category_id: services_category.id)
Subcategory.where(name: 'legal', category_id: services_category.id).first_or_create(name: 'legal', category_id: services_category.id)
Subcategory.where(name: 'lessons', category_id: services_category.id).first_or_create(name: 'lessons', category_id: services_category.id)
Subcategory.where(name: 'marine', category_id: services_category.id).first_or_create(name: 'marine', category_id: services_category.id)
Subcategory.where(name: 'pet', category_id: services_category.id).first_or_create(name: 'pet', category_id: services_category.id)
Subcategory.where(name: 'real estate', category_id: services_category.id).first_or_create(name: 'real estate', category_id: services_category.id)
Subcategory.where(name: 'skilled trade', category_id: services_category.id).first_or_create(name: 'skilled trade', category_id: services_category.id)
Subcategory.where(name: 'sm biz ads', category_id: services_category.id).first_or_create(name: 'sm biz ads', category_id: services_category.id)
Subcategory.where(name: 'therapeutic', category_id: services_category.id).first_or_create(name: 'therapeutic', category_id: services_category.id)
Subcategory.where(name: 'travel/vacation', category_id: services_category.id).first_or_create(name: 'travel/vacation', category_id: services_category.id)
Subcategory.where(name: 'write/ed/tr8', category_id: services_category.id).first_or_create(name: 'write/ed/tr8', category_id: services_category.id)

Subcategory.where(name: 'accounting+finance', category_id: jobs_category.id).first_or_create(name: 'accounting+finance', category_id: jobs_category.id)
Subcategory.where(name: 'admin/office', category_id: jobs_category.id).first_or_create(name: 'admin/office', category_id: jobs_category.id)
Subcategory.where(name: 'art/media/design', category_id: jobs_category.id).first_or_create(name: 'art/media/design', category_id: jobs_category.id)
Subcategory.where(name: 'biotech/science', category_id: jobs_category.id).first_or_create(name: 'biotech/science', category_id: jobs_category.id)
Subcategory.where(name: 'business/mgmt', category_id: jobs_category.id).first_or_create(name: 'business/mgmt', category_id: jobs_category.id)
Subcategory.where(name: 'food/bev/hosp', category_id: jobs_category.id).first_or_create(name: 'food/bev/hosp', category_id: jobs_category.id)
Subcategory.where(name: 'general labor', category_id: jobs_category.id).first_or_create(name: 'general labor', category_id: jobs_category.id)
Subcategory.where(name: 'government', category_id: jobs_category.id).first_or_create(name: 'government', category_id: jobs_category.id)
Subcategory.where(name: 'human resources', category_id: jobs_category.id).first_or_create(name: 'human resources', category_id: jobs_category.id)
Subcategory.where(name: 'internet engineers', category_id: jobs_category.id).first_or_create(name: 'internet engineers', category_id: jobs_category.id)
Subcategory.where(name: 'legal/paralegal', category_id: jobs_category.id).first_or_create(name: 'legal/paralegal', category_id: jobs_category.id)
Subcategory.where(name: 'manufacturing', category_id: jobs_category.id).first_or_create(name: 'manufacturing', category_id: jobs_category.id)
Subcategory.where(name: 'marketing/pr/ad', category_id: jobs_category.id).first_or_create(name: 'marketing/pr/ad', category_id: jobs_category.id)
Subcategory.where(name: 'medical/health', category_id: jobs_category.id).first_or_create(name: 'medical/health', category_id: jobs_category.id)
Subcategory.where(name: 'nonprofit sector', category_id: jobs_category.id).first_or_create(name: 'nonprofit sector', category_id: jobs_category.id)
Subcategory.where(name: 'real estate', category_id: jobs_category.id).first_or_create(name: 'real estate', category_id: jobs_category.id)
Subcategory.where(name: 'retail wholesale', category_id: jobs_category.id).first_or_create(name: 'retail wholesale', category_id: jobs_category.id)
Subcategory.where(name: 'sales/biz dev', category_id: jobs_category.id).first_or_create(name: 'sales/biz dev', category_id: jobs_category.id)
Subcategory.where(name: 'salon/spa/fitness', category_id: jobs_category.id).first_or_create(name: 'salon/spa/fitness', category_id: jobs_category.id)
Subcategory.where(name: 'security', category_id: jobs_category.id).first_or_create(name: 'security', category_id: jobs_category.id)
Subcategory.where(name: 'skilled trade/craft', category_id: jobs_category.id).first_or_create(name: 'skilled trade/craft', category_id: jobs_category.id)
Subcategory.where(name: 'software/qa/dba', category_id: jobs_category.id).first_or_create(name: 'software/qa/dba', category_id: jobs_category.id)
Subcategory.where(name: 'systems/network', category_id: jobs_category.id).first_or_create(name: 'systems/network', category_id: jobs_category.id)
Subcategory.where(name: 'technical support', category_id: jobs_category.id).first_or_create(name: 'technical support', category_id: jobs_category.id)
Subcategory.where(name: 'transport', category_id: jobs_category.id).first_or_create(name: 'transport', category_id: jobs_category.id)
Subcategory.where(name: 'tv/film/video', category_id: jobs_category.id).first_or_create(name: 'tv/film/video', category_id: jobs_category.id)
Subcategory.where(name: 'web/info design', category_id: jobs_category.id).first_or_create(name: 'web/info design', category_id: jobs_category.id)
Subcategory.where(name: 'writing/editing', category_id: jobs_category.id).first_or_create(name: 'writing/editing', category_id: jobs_category.id)
Subcategory.where(name: '[ETC]', category_id: jobs_category.id).first_or_create(name: '[ETC]', category_id: jobs_category.id)
Subcategory.where(name: '[part-time]', category_id: jobs_category.id).first_or_create(name: '[part-time]', category_id: jobs_category.id)

Subcategory.where(name: 'apple', category_id: discussionforums_category.id).first_or_create(name: 'apple', category_id: discussionforums_category.id)
Subcategory.where(name: 'arts', category_id: discussionforums_category.id).first_or_create(name: 'arts', category_id: discussionforums_category.id)
Subcategory.where(name: 'atheist', category_id: discussionforums_category.id).first_or_create(name: 'atheist', category_id: discussionforums_category.id)
Subcategory.where(name: 'autos', category_id: discussionforums_category.id).first_or_create(name: 'autos', category_id: discussionforums_category.id)
Subcategory.where(name: 'beauty', category_id: discussionforums_category.id).first_or_create(name: 'beauty', category_id: discussionforums_category.id)
Subcategory.where(name: 'bikes', category_id: discussionforums_category.id).first_or_create(name: 'bikes', category_id: discussionforums_category.id)
Subcategory.where(name: 'celebs', category_id: discussionforums_category.id).first_or_create(name: 'celebs', category_id: discussionforums_category.id)
Subcategory.where(name: 'comp', category_id: discussionforums_category.id).first_or_create(name: 'comp', category_id: discussionforums_category.id)
Subcategory.where(name: 'crafts', category_id: discussionforums_category.id).first_or_create(name: 'crafts', category_id: discussionforums_category.id)
Subcategory.where(name: 'diet', category_id: discussionforums_category.id).first_or_create(name: 'diet', category_id: discussionforums_category.id)
Subcategory.where(name: 'divorce', category_id: discussionforums_category.id).first_or_create(name: 'divorce', category_id: discussionforums_category.id)
Subcategory.where(name: 'dying', category_id: discussionforums_category.id).first_or_create(name: 'dying', category_id: discussionforums_category.id)
Subcategory.where(name: 'eco', category_id: discussionforums_category.id).first_or_create(name: 'eco', category_id: discussionforums_category.id)
Subcategory.where(name: 'education', category_id: discussionforums_category.id).first_or_create(name: 'education', category_id: discussionforums_category.id)
Subcategory.where(name: 'feedbk', category_id: discussionforums_category.id).first_or_create(name: 'feedbk', category_id: discussionforums_category.id)
Subcategory.where(name: 'film', category_id: discussionforums_category.id).first_or_create(name: 'film', category_id: discussionforums_category.id)
Subcategory.where(name: 'fitness', category_id: discussionforums_category.id).first_or_create(name: 'fitness', category_id: discussionforums_category.id)
Subcategory.where(name: 'fixit', category_id: discussionforums_category.id).first_or_create(name: 'fixit', category_id: discussionforums_category.id)
Subcategory.where(name: 'food', category_id: discussionforums_category.id).first_or_create(name: 'food', category_id: discussionforums_category.id)
Subcategory.where(name: 'frugal', category_id: discussionforums_category.id).first_or_create(name: 'frugal', category_id: discussionforums_category.id)
Subcategory.where(name: 'gaming', category_id: discussionforums_category.id).first_or_create(name: 'gaming', category_id: discussionforums_category.id)
Subcategory.where(name: 'garden', category_id: discussionforums_category.id).first_or_create(name: 'garden', category_id: discussionforums_category.id)
Subcategory.where(name: 'haiku', category_id: discussionforums_category.id).first_or_create(name: 'haiku', category_id: discussionforums_category.id)
Subcategory.where(name: 'help', category_id: discussionforums_category.id).first_or_create(name: 'help', category_id: discussionforums_category.id)
Subcategory.where(name: 'history', category_id: discussionforums_category.id).first_or_create(name: 'history', category_id: discussionforums_category.id)
Subcategory.where(name: 'housing', category_id: discussionforums_category.id).first_or_create(name: 'housing', category_id: discussionforums_category.id)
Subcategory.where(name: 'jobs', category_id: discussionforums_category.id).first_or_create(name: 'jobs', category_id: discussionforums_category.id)
Subcategory.where(name: 'jokes', category_id: discussionforums_category.id).first_or_create(name: 'jokes', category_id: discussionforums_category.id)
Subcategory.where(name: 'kinks', category_id: discussionforums_category.id).first_or_create(name: 'kinks', category_id: discussionforums_category.id)
Subcategory.where(name: 'legal', category_id: discussionforums_category.id).first_or_create(name: 'legal', category_id: discussionforums_category.id)
Subcategory.where(name: 'linux', category_id: discussionforums_category.id).first_or_create(name: 'linux', category_id: discussionforums_category.id)
Subcategory.where(name: 'm4m', category_id: discussionforums_category.id).first_or_create(name: 'm4m', category_id: discussionforums_category.id)
Subcategory.where(name: 'manners', category_id: discussionforums_category.id).first_or_create(name: 'manners', category_id: discussionforums_category.id)
Subcategory.where(name: 'marriage', category_id: discussionforums_category.id).first_or_create(name: 'marriage', category_id: discussionforums_category.id)
Subcategory.where(name: 'media', category_id: discussionforums_category.id).first_or_create(name: 'media', category_id: discussionforums_category.id)
Subcategory.where(name: 'money', category_id: discussionforums_category.id).first_or_create(name: 'money', category_id: discussionforums_category.id)
Subcategory.where(name: 'motorcycle', category_id: discussionforums_category.id).first_or_create(name: 'motorcycle', category_id: discussionforums_category.id)
Subcategory.where(name: 'music', category_id: discussionforums_category.id).first_or_create(name: 'music', category_id: discussionforums_category.id)
Subcategory.where(name: 'nonprofit', category_id: discussionforums_category.id).first_or_create(name: 'nonprofit', category_id: discussionforums_category.id)
Subcategory.where(name: 'open', category_id: discussionforums_category.id).first_or_create(name: 'open', category_id: discussionforums_category.id)
Subcategory.where(name: 'outdoor', category_id: discussionforums_category.id).first_or_create(name: 'outdoor', category_id: discussionforums_category.id)
Subcategory.where(name: 'over 50', category_id: discussionforums_category.id).first_or_create(name: 'over 50', category_id: discussionforums_category.id)
Subcategory.where(name: 'parent', category_id: discussionforums_category.id).first_or_create(name: 'parent', category_id: discussionforums_category.id)
Subcategory.where(name: 'pets', category_id: discussionforums_category.id).first_or_create(name: 'pets', category_id: discussionforums_category.id)
Subcategory.where(name: 'philosophy', category_id: discussionforums_category.id).first_or_create(name: 'philosophy', category_id: discussionforums_category.id)
Subcategory.where(name: 'photo', category_id: discussionforums_category.id).first_or_create(name: 'photo', category_id: discussionforums_category.id)
Subcategory.where(name: 'p.o.c.', category_id: discussionforums_category.id).first_or_create(name: 'p.o.c.', category_id: discussionforums_category.id)
Subcategory.where(name: 'politics', category_id: discussionforums_category.id).first_or_create(name: 'politics', category_id: discussionforums_category.id)
Subcategory.where(name: 'psychology', category_id: discussionforums_category.id).first_or_create(name: 'psychology', category_id: discussionforums_category.id)
Subcategory.where(name: 'queer', category_id: discussionforums_category.id).first_or_create(name: 'queer', category_id: discussionforums_category.id)
Subcategory.where(name: 'recover', category_id: discussionforums_category.id).first_or_create(name: 'recover', category_id: discussionforums_category.id)
Subcategory.where(name: 'religion', category_id: discussionforums_category.id).first_or_create(name: 'religion', category_id: discussionforums_category.id)
Subcategory.where(name: 'romance', category_id: discussionforums_category.id).first_or_create(name: 'romance', category_id: discussionforums_category.id)
Subcategory.where(name: 'science', category_id: discussionforums_category.id).first_or_create(name: 'science', category_id: discussionforums_category.id)
Subcategory.where(name: 'spirit', category_id: discussionforums_category.id).first_or_create(name: 'spirit', category_id: discussionforums_category.id)
Subcategory.where(name: 'sports', category_id: discussionforums_category.id).first_or_create(name: 'sports', category_id: discussionforums_category.id)
Subcategory.where(name: 'tax', category_id: discussionforums_category.id).first_or_create(name: 'tax', category_id: discussionforums_category.id)
Subcategory.where(name: 'travel', category_id: discussionforums_category.id).first_or_create(name: 'travel', category_id: discussionforums_category.id)
Subcategory.where(name: 'tv', category_id: discussionforums_category.id).first_or_create(name: 'tv', category_id: discussionforums_category.id)
Subcategory.where(name: 'vegan', category_id: discussionforums_category.id).first_or_create(name: 'vegan', category_id: discussionforums_category.id)
Subcategory.where(name: 'w4w', category_id: discussionforums_category.id).first_or_create(name: 'w4w', category_id: discussionforums_category.id)
Subcategory.where(name: 'wed', category_id: discussionforums_category.id).first_or_create(name: 'wed', category_id: discussionforums_category.id)
Subcategory.where(name: 'wine', category_id: discussionforums_category.id).first_or_create(name: 'wine', category_id: discussionforums_category.id)
Subcategory.where(name: 'words', category_id: discussionforums_category.id).first_or_create(name: 'words', category_id: discussionforums_category.id)
Subcategory.where(name: 'writing', category_id: discussionforums_category.id).first_or_create(name: 'writing', category_id: discussionforums_category.id)
Subcategory.where(name: 'yoga', category_id: discussionforums_category.id).first_or_create(name: 'yoga', category_id: discussionforums_category.id)
